import { useState, useCallback } from "react";
import { useAppContext, type ReportData, type ReportHistoryItem } from "@/store/AppContext";
import { cn } from "@/lib/utils";
import { openArticleLink } from "@/lib/openArticleLink";
import {
  FileText,
  Loader2,
  Send,
  Download,
  ExternalLink,
  Star,
  BarChart3,
  FileCode,
  FileType,
  CheckCircle2,
} from "lucide-react";

const REPORT_COUNT_PRESETS = [20, 30, 50, 80, 100];
const REPORT_MAX_FEEDS_PRESETS = [10, 15, 20, 30, 40];

function triggerDownload(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ReportPage() {
  const {
    reportKeyword,
    reportMinCount,
    reportMaxFeeds,
    reportWithIllustrations,
    reportLoading,
    reportError,
    report,
    reportFeeds,
    reportHistory,
    setReportKeyword,
    setReportMinCount,
    setReportMaxFeeds,
    setReportWithIllustrations,
    runGenerateReport,
    selectReportHistory,
  } = useAppContext();

  const [downloadMsg, setDownloadMsg] = useState("");

  const showDownloadMsg = (msg: string) => {
    setDownloadMsg(msg);
    setTimeout(() => setDownloadMsg(""), 3000);
  };

  const safeFilename = (kw: string) =>
    kw.replace(/[\\/:*?"<>|]/g, "_").slice(0, 30);

  const buildMarkdown = useCallback(
    (r: ReportData): string => {
      const lines = [
        `# ${r.title}`,
        "",
        `> 生成时间: ${new Date().toLocaleString("zh-CN")}`,
        "",
        `## 概览`,
        "",
        r.overview,
        "",
      ];
      const v = r.report_visuals;
      if (v?.primary_image_url) {
        lines.push(
          `## 配图 / 一图读懂`,
          "",
          `![${v.caption || "报告配图"}](${v.primary_image_url})`,
          ""
        );
        if (v.more_image_urls?.length) {
          for (const u of v.more_image_urls) {
            lines.push(`![](${u})`, "");
          }
        }
        if (v.caption) lines.push(v.caption, "");
        if (v.image_prompt_hint) {
          lines.push(`*文生图提示：${v.image_prompt_hint}*`, "");
        }
      } else if (v?.image_prompt_hint || v?.caption) {
        lines.push(`## 配图说明`, "");
        if (v.caption) lines.push(v.caption, "");
        if (v.image_prompt_hint) {
          lines.push(`文生图提示：${v.image_prompt_hint}`, "");
        }
      }
      lines.push(
        `## 详细分析`,
        "",
        r.analysis,
        "",
        `## Top 笔记`,
        "",
        ...r.top_feeds.map((f, i) => {
          const title = (f.title as string) || "无标题";
          const score = f.score !== undefined ? ` (评分: ${f.score})` : "";
          const link = (f.link as string) || "";
          const reason = (f.reason as string) || "";
          return `${i + 1}. **${title}**${score}${link ? ` - [查看原文](${link})` : ""}${reason ? `\n   ${reason}` : ""}`;
        }),
        "",
        `## 行动建议`,
        "",
        ...r.recommendations.map((x, i) => `${i + 1}. ${x}`),
        "",
        "---",
        `*Generated by RedBook Desktop*`,
      );
      return lines.join("\n");
    },
    []
  );

  const buildHTML = useCallback((r: ReportData): string => {
    const topFeedRows = r.top_feeds
      .map((f, i) => {
        const title = (f.title as string) || "无标题";
        const score = f.score !== undefined ? Number(f.score).toFixed(1) : "-";
        const link = (f.link as string) || "#";
        const reason = (f.reason as string) || "";
        return `<tr><td>${i + 1}</td><td>${title}</td><td>${score}</td><td>${reason}</td><td><a href="${link}" target="_blank">查看</a></td></tr>`;
      })
      .join("\n");
    const recItems = r.recommendations.map((x) => `<li>${x}</li>`).join("\n");
    const vis = r.report_visuals;
    let visualsBlock = "";
    if (vis?.primary_image_url) {
      const src = JSON.stringify(vis.primary_image_url);
      const alt = JSON.stringify(vis.caption || "报告配图");
      visualsBlock = `<h2>配图 / 一图读懂</h2><p><img src=${src} alt=${alt} style="max-width:100%;height:auto;border-radius:8px;border:1px solid #e5e7eb"/></p>`;
      if (vis.more_image_urls?.length) {
        for (const u of vis.more_image_urls) {
          visualsBlock += `<p><img src=${JSON.stringify(u)} alt="" style="max-width:100%;height:auto;border-radius:8px"/></p>`;
        }
      }
      if (vis.caption) {
        visualsBlock += `<div class="overview"><p>${vis.caption}</p></div>`;
      }
      if (vis.image_prompt_hint) {
        visualsBlock += `<p style="font-size:13px;color:#6b7280"><em>文生图提示：</em>${vis.image_prompt_hint}</p>`;
      }
    } else if (vis?.image_prompt_hint || vis?.caption) {
      visualsBlock = "<h2>配图说明</h2>";
      if (vis.caption) visualsBlock += `<p>${vis.caption}</p>`;
      if (vis.image_prompt_hint) {
        visualsBlock += `<p style="font-size:13px;color:#6b7280">文生图提示：${vis.image_prompt_hint}</p>`;
      }
    }
    return `<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="utf-8"><title>${r.title}</title>
<style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"PingFang SC","Microsoft YaHei",sans-serif;max-width:800px;margin:2rem auto;padding:0 1rem;color:#1a1a1a;line-height:1.7}
h1{color:#e11d48}h2{color:#374151;border-bottom:1px solid #e5e7eb;padding-bottom:.5rem}
table{width:100%;border-collapse:collapse;margin:1rem 0}th,td{padding:.5rem .75rem;border:1px solid #e5e7eb;text-align:left}
th{background:#f9fafb;font-weight:600}a{color:#e11d48;text-decoration:none}a:hover{text-decoration:underline}
.overview{background:#eff6ff;padding:1rem;border-radius:.5rem;border:1px solid #bfdbfe;margin:1rem 0}
.recs{background:#f0fdf4;padding:1rem;border-radius:.5rem;border:1px solid #bbf7d0;margin:1rem 0}
.analysis{white-space:pre-wrap}
footer{margin-top:2rem;color:#9ca3af;font-size:12px;text-align:center}</style></head>
<body><h1>${r.title}</h1>
<div class="overview"><p>${r.overview}</p></div>
${visualsBlock}
<h2>详细分析</h2><div class="analysis">${r.analysis.replace(/\n/g, "<br>")}</div>
<h2>Top 笔记</h2><table><thead><tr><th>#</th><th>标题</th><th>评分</th><th>理由</th><th>链接</th></tr></thead>
<tbody>${topFeedRows}</tbody></table>
<h2>行动建议</h2><div class="recs"><ol>${recItems}</ol></div>
<footer>Generated by RedBook Desktop - ${new Date().toLocaleString("zh-CN")}</footer>
</body></html>`;
  }, []);

  const exportMarkdown = () => {
    if (!report) return;
    const md = buildMarkdown(report);
    if (!md) return;
    triggerDownload(
      md,
      `报告-${safeFilename(reportKeyword)}.md`,
      "text/markdown;charset=utf-8"
    );
    showDownloadMsg("Markdown 报告已下载");
  };

  const exportHTML = () => {
    if (!report) return;
    const html = buildHTML(report);
    if (!html) return;
    triggerDownload(
      html,
      `报告-${safeFilename(reportKeyword)}.html`,
      "text/html;charset=utf-8"
    );
    showDownloadMsg("HTML 报告已下载");
  };

  const exportJSON = () => {
    if (!report) return;
    const data = {
      keyword: reportKeyword,
      generated_at: new Date().toISOString(),
      report,
      feeds_count: reportFeeds.length,
    };
    triggerDownload(
      JSON.stringify(data, null, 2),
      `报告-${safeFilename(reportKeyword)}.json`,
      "application/json;charset=utf-8"
    );
    showDownloadMsg("JSON 数据已下载");
  };

  return (
    <div className="flex w-full min-h-0 min-h-[min(100%,32rem)]">
      <div className="w-56 sm:w-64 shrink-0 border-r border-gray-200 bg-white overflow-y-auto scrollbar-thin max-h-[calc(100vh-3rem)]">
        <div className="p-4 border-b border-gray-100">
          <h3 className="text-sm font-medium text-gray-700">历史报告</h3>
        </div>
        {reportHistory.length === 0 ? (
          <p className="p-4 text-xs text-gray-400">暂无报告</p>
        ) : (
          <div className="divide-y divide-gray-100">
            {reportHistory.map((r: ReportHistoryItem, idx: number) => (
              <button
                key={`${r.keyword}-${r.date}-${idx}`}
                type="button"
                onClick={() => selectReportHistory(r)}
                className="w-full text-left p-3 hover:bg-gray-50 transition-colors"
              >
                <p className="text-sm font-medium text-gray-700 truncate">
                  {r.keyword}
                </p>
                <p className="text-xs text-gray-400 mt-0.5">{r.date}</p>
              </button>
            ))}
          </div>
        )}
      </div>

      <div className="flex-1 flex flex-col min-w-0 min-h-0">
        <div className="px-6 py-4 bg-white border-b border-gray-200 shrink-0">
          <div className="flex items-center gap-2 flex-wrap">
            <BarChart3 className="w-5 h-5 text-brand-500" />
            <h2 className="font-semibold text-gray-800">内容报告</h2>
            {reportLoading && (
              <span className="text-xs text-amber-600">
                生成在后台进行，可切换页面，完成后返回查看
              </span>
            )}
          </div>
          <div className="flex items-center gap-2 mt-3 flex-wrap">
            <input
              value={reportKeyword}
              onChange={(e) => setReportKeyword(e.target.value)}
              onKeyDown={(e) =>
                e.key === "Enter" && !reportLoading && void runGenerateReport()
              }
              placeholder="输入关键词生成分析报告..."
              className="flex-1 min-w-[200px] px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-brand-200 focus:border-brand-400"
            />
            <button
              type="button"
              onClick={() => void runGenerateReport()}
              disabled={reportLoading || !reportKeyword.trim()}
              className="px-5 py-2.5 bg-brand-500 text-white text-sm font-medium rounded-lg hover:bg-brand-600 disabled:opacity-50 flex items-center gap-1.5"
            >
              {reportLoading ? (
                <Loader2 size={16} className="animate-spin" />
              ) : (
                <Send size={16} />
              )}
              生成报告
            </button>
          </div>
          <div className="mt-3">
            <span className="text-xs text-gray-500 mr-2">检索条数</span>
            <div className="inline-flex gap-1 flex-wrap mt-1">
              {REPORT_COUNT_PRESETS.map((n) => (
                <button
                  key={n}
                  type="button"
                  onClick={() => setReportMinCount(n)}
                  className={cn(
                    "px-2.5 py-1 text-xs rounded-md border transition-colors",
                    reportMinCount === n
                      ? "bg-brand-50 border-brand-300 text-brand-700"
                      : "border-gray-200 text-gray-600 hover:bg-gray-50"
                  )}
                >
                  {n}
                </button>
              ))}
            </div>
          </div>
          <div className="mt-3 flex flex-wrap items-center gap-3">
            <div>
              <span className="text-xs text-gray-500 mr-2 block mb-1">
                送入报告的笔记条数（屏蔽词后至多）
              </span>
              <div className="inline-flex gap-1 flex-wrap">
                {REPORT_MAX_FEEDS_PRESETS.map((n) => (
                  <button
                    key={n}
                    type="button"
                    onClick={() => setReportMaxFeeds(n)}
                    className={cn(
                      "px-2.5 py-1 text-xs rounded-md border transition-colors",
                      reportMaxFeeds === n
                        ? "bg-brand-50 border-brand-300 text-brand-700"
                        : "border-gray-200 text-gray-600 hover:bg-gray-50"
                    )}
                  >
                    {n}
                  </button>
                ))}
                <input
                  type="number"
                  min={1}
                  max={40}
                  value={reportMaxFeeds}
                  onChange={(e) =>
                    setReportMaxFeeds(Number(e.target.value) || 1)
                  }
                  className="w-14 rounded-md border border-gray-300 px-2 py-1 text-xs focus:border-brand-400 focus:outline-none focus:ring-1 focus:ring-brand-200"
                  title="1–40"
                />
              </div>
            </div>
            <label className="flex items-center gap-2 cursor-pointer text-xs text-gray-600 mt-5">
              <input
                type="checkbox"
                checked={reportWithIllustrations}
                onChange={(e) => setReportWithIllustrations(e.target.checked)}
                className="rounded border-gray-300 text-brand-600 focus:ring-brand-200"
              />
              配图与文生图提示（从笔记封面选图 + 可选画面描述）
            </label>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-6 scrollbar-thin min-h-[200px]">
          {reportError && (
            <div className="p-4 bg-red-50 border border-red-200 rounded-lg text-sm text-red-600 mb-4">
              {reportError}
            </div>
          )}

          {reportLoading && (
            <div className="text-center py-20">
              <Loader2 className="w-8 h-8 animate-spin text-brand-500 mx-auto" />
              <p className="text-sm text-gray-500 mt-3">
                正在搜索并生成报告，请稍候...
              </p>
            </div>
          )}

          {!report && !reportLoading && (
            <div className="text-center py-20 text-gray-400">
              <FileText className="w-12 h-12 mx-auto mb-3 opacity-40" />
              <p>输入关键词生成内容分析报告</p>
            </div>
          )}

          {report && !reportLoading && (
            <div className="space-y-6 max-w-3xl">
              {typeof report.filtered_by_block_words === "number" &&
                report.filtered_by_block_words > 0 && (
                  <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg text-sm text-amber-900">
                    生成报告前已按「设置」屏蔽词过滤 {report.filtered_by_block_words}{" "}
                    篇候选笔记。
                  </div>
                )}
              <div>
                <h3 className="text-lg font-bold text-gray-800 mb-3">
                  {report.title}
                </h3>
                <div className="flex items-center gap-2 flex-wrap">
                  <span className="text-xs text-gray-400 mr-2">下载报告：</span>
                  <button
                    type="button"
                    onClick={exportMarkdown}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs border border-gray-300 rounded-lg hover:bg-gray-50 hover:border-brand-300 transition-colors"
                  >
                    <FileText size={14} className="text-gray-500" /> Markdown
                  </button>
                  <button
                    type="button"
                    onClick={exportHTML}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs border border-gray-300 rounded-lg hover:bg-gray-50 hover:border-brand-300 transition-colors"
                  >
                    <FileCode size={14} className="text-gray-500" /> HTML 网页
                  </button>
                  <button
                    type="button"
                    onClick={exportJSON}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs border border-gray-300 rounded-lg hover:bg-gray-50 hover:border-brand-300 transition-colors"
                  >
                    <FileType size={14} className="text-gray-500" /> JSON 数据
                  </button>
                  {downloadMsg && (
                    <span className="text-xs text-green-600 flex items-center gap-1 ml-2">
                      <CheckCircle2 size={14} /> {downloadMsg}
                    </span>
                  )}
                </div>
              </div>

              <div className="p-4 bg-blue-50 border border-blue-200 rounded-xl">
                <p className="text-sm text-blue-800 whitespace-pre-wrap">
                  {report.overview}
                </p>
              </div>

              {report.report_visuals?.primary_image_url ? (
                <div className="p-4 bg-white rounded-xl border border-gray-200">
                  <h4 className="font-medium text-gray-800 mb-2">
                    配图 / 一图读懂
                  </h4>
                  <img
                    src={report.report_visuals.primary_image_url}
                    alt={report.report_visuals.caption || "报告配图"}
                    className="max-w-full rounded-lg border border-gray-200"
                  />
                  {report.report_visuals.caption && (
                    <p className="text-sm text-gray-600 mt-2">
                      {report.report_visuals.caption}
                    </p>
                  )}
                  {report.report_visuals.more_image_urls &&
                    report.report_visuals.more_image_urls.length > 0 && (
                      <div className="mt-3 flex flex-wrap gap-2">
                        {report.report_visuals.more_image_urls.map((u) => (
                          <img
                            key={u}
                            src={u}
                            alt=""
                            className="h-24 w-auto rounded border border-gray-100 object-cover"
                          />
                        ))}
                      </div>
                    )}
                  {report.report_visuals.image_prompt_hint && (
                    <p className="text-xs text-gray-500 mt-2 whitespace-pre-wrap">
                      <span className="font-medium text-gray-600">
                        文生图提示：
                      </span>
                      {report.report_visuals.image_prompt_hint}
                    </p>
                  )}
                </div>
              ) : report.report_visuals &&
                (report.report_visuals.caption ||
                  report.report_visuals.image_prompt_hint) ? (
                <div className="p-4 bg-white rounded-xl border border-gray-200">
                  <h4 className="font-medium text-gray-800 mb-2">配图说明</h4>
                  {report.report_visuals.caption && (
                    <p className="text-sm text-gray-600">
                      {report.report_visuals.caption}
                    </p>
                  )}
                  {report.report_visuals.image_prompt_hint && (
                    <p className="text-xs text-gray-500 mt-2 whitespace-pre-wrap">
                      文生图提示：{report.report_visuals.image_prompt_hint}
                    </p>
                  )}
                </div>
              ) : null}

              <div className="p-4 bg-white rounded-xl border border-gray-200">
                <h4 className="font-medium text-gray-800 mb-2">详细分析</h4>
                <p className="text-sm text-gray-600 whitespace-pre-wrap leading-relaxed">
                  {report.analysis}
                </p>
              </div>

              {report.top_feeds.length > 0 && (
                <div>
                  <h4 className="font-medium text-gray-800 mb-3">
                    Top 笔记（{report.top_feeds.length} 篇）
                  </h4>
                  <div className="space-y-2">
                    {report.top_feeds.map((f, idx) => (
                      <div
                        key={idx}
                        className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200"
                      >
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2">
                            <span className="text-xs text-gray-400 flex-shrink-0">
                              #{idx + 1}
                            </span>
                            <span className="text-sm font-medium text-gray-700 truncate">
                              {(f.title as string) || "无标题"}
                            </span>
                            {f.score !== undefined && (
                              <span className="flex-shrink-0 inline-flex items-center gap-0.5 text-xs text-amber-600">
                                <Star
                                  size={12}
                                  className="fill-amber-500 text-amber-500"
                                />
                                {Number(f.score).toFixed(1)}
                              </span>
                            )}
                          </div>
                          {f.reason && (
                            <p className="text-xs text-gray-400 mt-1 ml-6 truncate">
                              {f.reason as string}
                            </p>
                          )}
                        </div>
                        {f.link && (
                          <button
                            type="button"
                            onClick={() =>
                              void openArticleLink(f.link as string)
                            }
                            className="text-brand-500 hover:text-brand-600 flex-shrink-0 ml-2 p-0.5"
                            title="在已登录的调试浏览器中打开"
                          >
                            <ExternalLink size={14} />
                          </button>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {report.recommendations.length > 0 && (
                <div className="p-4 bg-green-50 border border-green-200 rounded-xl">
                  <h4 className="font-medium text-green-800 mb-2">行动建议</h4>
                  <ol className="list-decimal list-inside space-y-1.5">
                    {report.recommendations.map((r, idx) => (
                      <li key={idx} className="text-sm text-green-700">
                        {r}
                      </li>
                    ))}
                  </ol>
                </div>
              )}

              <div className="py-4 border-t border-gray-100 flex items-center gap-2">
                <Download size={14} className="text-gray-400" />
                <span className="text-xs text-gray-400">下载：</span>
                <button
                  type="button"
                  onClick={exportMarkdown}
                  className="text-xs text-brand-600 hover:text-brand-700 underline"
                >
                  Markdown
                </button>
                <span className="text-gray-300">|</span>
                <button
                  type="button"
                  onClick={exportHTML}
                  className="text-xs text-brand-600 hover:text-brand-700 underline"
                >
                  HTML
                </button>
                <span className="text-gray-300">|</span>
                <button
                  type="button"
                  onClick={exportJSON}
                  className="text-xs text-brand-600 hover:text-brand-700 underline"
                >
                  JSON
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
