import { useState, useCallback } from "react";
import { api } from "@/services/api";
import {
  FileText,
  Loader2,
  Send,
  Download,
  ExternalLink,
  Star,
  BarChart3,
} from "lucide-react";

interface Report {
  title: string;
  overview: string;
  top_feeds: Array<Record<string, unknown>>;
  analysis: string;
  recommendations: string[];
}

export function ReportPage() {
  const [keyword, setKeyword] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [report, setReport] = useState<Report | null>(null);
  const [reports, setReports] = useState<Array<{ keyword: string; report: Report; date: string }>>([]);

  const generateReport = useCallback(async () => {
    const q = keyword.trim();
    if (!q) return;
    setLoading(true);
    setError("");
    setReport(null);

    try {
      const searchRes = await api.searchFeeds(q);
      const feeds = searchRes.feeds || [];
      if (feeds.length === 0) {
        setError("未找到相关笔记");
        setLoading(false);
        return;
      }

      const res = await api.aiGenerateReport({
        feeds: feeds.slice(0, 15),
        keyword: q,
      });
      setReport(res.report);
      setReports((prev) => [
        { keyword: q, report: res.report, date: new Date().toLocaleString("zh-CN") },
        ...prev,
      ]);
    } catch (e) {
      setError(e instanceof Error ? e.message : "报告生成失败");
    } finally {
      setLoading(false);
    }
  }, [keyword]);

  const buildMarkdownLines = useCallback((): string[] => {
    if (!report) return [];
    return [
      `# ${report.title}`,
      "",
      `## 概览`,
      report.overview,
      "",
      `## 详细分析`,
      report.analysis,
      "",
      `## Top 笔记`,
      ...report.top_feeds.map((f, i) => {
        const title = (f.title as string) || "无标题";
        const score = f.score !== undefined ? ` (评分: ${f.score})` : "";
        const link = (f.link as string) || "";
        return `${i + 1}. **${title}**${score}${link ? ` - [查看](${link})` : ""}`;
      }),
      "",
      `## 行动建议`,
      ...report.recommendations.map((r, i) => `${i + 1}. ${r}`),
    ];
  }, [report]);

  const exportMarkdown = useCallback(() => {
    const lines = buildMarkdownLines();
    if (!lines.length) return;
    const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `report-${keyword}-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [buildMarkdownLines, keyword]);

  const exportHTML = useCallback(() => {
    if (!report) return;
    const topFeedRows = report.top_feeds
      .map((f, i) => {
        const title = (f.title as string) || "无标题";
        const score = f.score !== undefined ? Number(f.score).toFixed(1) : "-";
        const link = (f.link as string) || "#";
        const reason = (f.reason as string) || "";
        return `<tr><td>${i + 1}</td><td>${title}</td><td>${score}</td><td>${reason}</td><td><a href="${link}" target="_blank">查看</a></td></tr>`;
      })
      .join("\n");
    const recItems = report.recommendations.map((r) => `<li>${r}</li>`).join("\n");
    const html = `<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="utf-8"><title>${report.title}</title>
<style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"PingFang SC",sans-serif;max-width:800px;margin:2rem auto;padding:0 1rem;color:#1a1a1a}
h1{color:#e11d48}h2{color:#374151;border-bottom:1px solid #e5e7eb;padding-bottom:.5rem}
table{width:100%;border-collapse:collapse;margin:1rem 0}th,td{padding:.5rem;border:1px solid #e5e7eb;text-align:left}
th{background:#f9fafb}a{color:#e11d48}.overview{background:#eff6ff;padding:1rem;border-radius:.5rem;border:1px solid #bfdbfe}
.recs{background:#f0fdf4;padding:1rem;border-radius:.5rem;border:1px solid #bbf7d0}</style></head>
<body><h1>${report.title}</h1>
<div class="overview"><p>${report.overview}</p></div>
<h2>详细分析</h2><p>${report.analysis.replace(/\n/g, "<br>")}</p>
<h2>Top 笔记</h2><table><thead><tr><th>#</th><th>标题</th><th>评分</th><th>理由</th><th>链接</th></tr></thead>
<tbody>${topFeedRows}</tbody></table>
<h2>行动建议</h2><div class="recs"><ol>${recItems}</ol></div>
<footer style="margin-top:2rem;color:#9ca3af;font-size:12px">Generated by RedBook Desktop - ${new Date().toLocaleString("zh-CN")}</footer>
</body></html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `report-${keyword}-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }, [report, keyword]);

  return (
    <div className="flex h-full">
      {/* Left: history */}
      <div className="w-64 border-r border-gray-200 bg-white overflow-y-auto scrollbar-thin">
        <div className="p-4 border-b border-gray-100">
          <h3 className="text-sm font-medium text-gray-700">历史报告</h3>
        </div>
        {reports.length === 0 ? (
          <p className="p-4 text-xs text-gray-400">暂无报告</p>
        ) : (
          <div className="divide-y divide-gray-100">
            {reports.map((r, idx) => (
              <button
                key={idx}
                onClick={() => setReport(r.report)}
                className="w-full text-left p-3 hover:bg-gray-50 transition-colors"
              >
                <p className="text-sm font-medium text-gray-700 truncate">{r.keyword}</p>
                <p className="text-xs text-gray-400 mt-0.5">{r.date}</p>
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Right: content */}
      <div className="flex-1 flex flex-col overflow-hidden">
        <div className="px-6 py-4 bg-white border-b border-gray-200">
          <div className="flex items-center gap-2">
            <BarChart3 className="w-5 h-5 text-brand-500" />
            <h2 className="font-semibold text-gray-800">内容报告</h2>
          </div>
          <div className="flex items-center gap-2 mt-3">
            <input
              value={keyword}
              onChange={(e) => setKeyword(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && !loading && generateReport()}
              placeholder="输入关键词生成分析报告..."
              className="flex-1 px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-brand-200 focus:border-brand-400"
            />
            <button
              onClick={generateReport}
              disabled={loading || !keyword.trim()}
              className="px-5 py-2.5 bg-brand-500 text-white text-sm font-medium rounded-lg hover:bg-brand-600 disabled:opacity-50 flex items-center gap-1.5"
            >
              {loading ? <Loader2 size={16} className="animate-spin" /> : <Send size={16} />}
              生成报告
            </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-6 scrollbar-thin">
          {error && (
            <div className="p-4 bg-red-50 border border-red-200 rounded-lg text-sm text-red-600 mb-4">
              {error}
            </div>
          )}

          {loading && (
            <div className="text-center py-20">
              <Loader2 className="w-8 h-8 animate-spin text-brand-500 mx-auto" />
              <p className="text-sm text-gray-500 mt-3">正在生成报告，请稍候...</p>
            </div>
          )}

          {!report && !loading && (
            <div className="text-center py-20 text-gray-400">
              <FileText className="w-12 h-12 mx-auto mb-3 opacity-40" />
              <p>输入关键词生成内容分析报告</p>
            </div>
          )}

          {report && !loading && (
            <div className="space-y-6 max-w-3xl">
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-bold text-gray-800">{report.title}</h3>
                <div className="flex gap-2">
                  <button
                    onClick={exportMarkdown}
                    className="flex items-center gap-1 px-3 py-1.5 text-xs border border-gray-300 rounded-lg hover:bg-gray-50"
                  >
                    <Download size={14} /> Markdown
                  </button>
                  <button
                    onClick={exportHTML}
                    className="flex items-center gap-1 px-3 py-1.5 text-xs border border-gray-300 rounded-lg hover:bg-gray-50"
                  >
                    <Download size={14} /> HTML
                  </button>
                </div>
              </div>

              <div className="p-4 bg-blue-50 border border-blue-200 rounded-xl">
                <p className="text-sm text-blue-800 whitespace-pre-wrap">{report.overview}</p>
              </div>

              <div className="p-4 bg-white rounded-xl border border-gray-200">
                <h4 className="font-medium text-gray-800 mb-2">详细分析</h4>
                <p className="text-sm text-gray-600 whitespace-pre-wrap leading-relaxed">
                  {report.analysis}
                </p>
              </div>

              {report.top_feeds.length > 0 && (
                <div>
                  <h4 className="font-medium text-gray-800 mb-3">
                    Top 笔记（{report.top_feeds.length} 篇）
                  </h4>
                  <div className="space-y-2">
                    {report.top_feeds.map((f, idx) => (
                      <div
                        key={idx}
                        className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200"
                      >
                        <div className="flex-1">
                          <span className="text-xs text-gray-400 mr-2">#{idx + 1}</span>
                          <span className="text-sm font-medium text-gray-700">
                            {(f.title as string) || "无标题"}
                          </span>
                          {f.score !== undefined && (
                            <span className="ml-2 inline-flex items-center gap-0.5 text-xs text-amber-600">
                              <Star size={12} className="fill-amber-500 text-amber-500" />
                              {Number(f.score).toFixed(1)}
                            </span>
                          )}
                        </div>
                        {f.link && (
                          <a
                            href={f.link as string}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-brand-500 hover:text-brand-600"
                          >
                            <ExternalLink size={14} />
                          </a>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {report.recommendations.length > 0 && (
                <div className="p-4 bg-green-50 border border-green-200 rounded-xl">
                  <h4 className="font-medium text-green-800 mb-2">行动建议</h4>
                  <ol className="list-decimal list-inside space-y-1">
                    {report.recommendations.map((r, idx) => (
                      <li key={idx} className="text-sm text-green-700">{r}</li>
                    ))}
                  </ol>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
